# Generated by Django 4.0.4 on 2022-05-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductItem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='product_image',
            new_name='image',
        ),
    ]
