# Generated by Django 4.0.4 on 2022-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductItem', '0002_rename_product_image_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customerimg'),
        ),
    ]
