# Generated by Django 4.0.4 on 2022-05-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductItem', '0003_alter_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
