# Generated by Django 4.0.4 on 2022-05-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductItem', '0004_remove_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='f_customer',
            new_name='customer',
        ),
    ]
